//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService1_demo.WebService_CRUD_demo_Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.shaw-yu.com/", ConfigurationName="WebService_CRUD_demo_Reference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name appr from namespace http://www.shaw-yu.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.shaw-yu.com/Appr_Div_Summary", ReplyAction="*")]
        WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse Appr_Div_Summary(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.shaw-yu.com/Appr_Div_Summary", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse> Appr_Div_SummaryAsync(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Appr_Div_SummaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Appr_Div_Summary", Namespace="http://www.shaw-yu.com/", Order=0)]
        public WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequestBody Body;
        
        public Appr_Div_SummaryRequest() {
        }
        
        public Appr_Div_SummaryRequest(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.shaw-yu.com/")]
    public partial class Appr_Div_SummaryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string start_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string end_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bfy;
        
        public Appr_Div_SummaryRequestBody() {
        }
        
        public Appr_Div_SummaryRequestBody(string appr, string start_date, string end_date, string bfy) {
            this.appr = appr;
            this.start_date = start_date;
            this.end_date = end_date;
            this.bfy = bfy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Appr_Div_SummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Appr_Div_SummaryResponse", Namespace="http://www.shaw-yu.com/", Order=0)]
        public WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponseBody Body;
        
        public Appr_Div_SummaryResponse() {
        }
        
        public Appr_Div_SummaryResponse(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.shaw-yu.com/")]
    public partial class Appr_Div_SummaryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Appr_Div_SummaryResult;
        
        public Appr_Div_SummaryResponseBody() {
        }
        
        public Appr_Div_SummaryResponseBody(string Appr_Div_SummaryResult) {
            this.Appr_Div_SummaryResult = Appr_Div_SummaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap>, WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap.Appr_Div_Summary(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest request) {
            return base.Channel.Appr_Div_Summary(request);
        }
        
        public string Appr_Div_Summary(string appr, string start_date, string end_date, string bfy) {
            WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest inValue = new WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest();
            inValue.Body = new WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequestBody();
            inValue.Body.appr = appr;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.bfy = bfy;
            WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse retVal = ((WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap)(this)).Appr_Div_Summary(inValue);
            return retVal.Body.Appr_Div_SummaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse> WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap.Appr_Div_SummaryAsync(WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest request) {
            return base.Channel.Appr_Div_SummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryResponse> Appr_Div_SummaryAsync(string appr, string start_date, string end_date, string bfy) {
            WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest inValue = new WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequest();
            inValue.Body = new WebService1_demo.WebService_CRUD_demo_Reference.Appr_Div_SummaryRequestBody();
            inValue.Body.appr = appr;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.bfy = bfy;
            return ((WebService1_demo.WebService_CRUD_demo_Reference.WebService1Soap)(this)).Appr_Div_SummaryAsync(inValue);
        }
    }
}
